# Generated by Django 4.2.4 on 2023-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
