# Generated by Django 4.2.4 on 2023-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
